### ISSUE TITLE
Xcode 8.1 - Can't return anything with SMCKit

### ISSUE THREAD

**Issue by PKBeam** [beltex/SMCKit#28]
Running this code (on MacBookPro13,2 with 10.12.1):

```
import Cocoa
import SMCKit

do {
    let fans = try SMCKit.fanCount()
    print(fans)
} catch {
    print("Error")
}
```

Prints "Error". It happens with fan speed, fan names, etc. What am I doing wrong?

**Comment by beltex** [comment]
Hello @PKBeam!

`open()` must be called first to get a connection to the SMC driver (and make sure to call `close()` when your done!). See [SMCKitTool](https://github.com/beltex/SMCKit/blob/master/SMCKitTool/main.swift#L309-L314) for an example. `README`/docs should be updated to make that clear, since a number of folks have asked about this, (so my bad!).

Hope that helps!

**P.S** New Macbook? Nice! :)

**Comment by PKBeam** [comment]
Ah, I see. Thanks.
